swagger: '2.0'
info:
  description: This is Persons api for udacity UdaConnect project
  version: 1.0.0
  title: Persons API
  contact:
    email: pasciano007@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /persons:
    get:
      summary: Return persons
      operationId: get
      description: |
        Retrive all persons in the database that might have connections
      produces:
        - application/json
      responses:
        200:
          description: persons retrived successfully from database
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
        400:
          description: bad input parameter
    post:
      summary: adds a person item
      operationId: post
      description: Adds a person to the database
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: person
          description: person to be added
          schema:
            $ref: '#/definitions/Person'
      responses:
        201:
          description: person created
        400:
          description: invalid input, person invalid
        409:
          description: an existing person already exists

  /persons/{person_id}:
    get:
      summary: Find a person by it's ID
      description: For valid response try integer IDs with value >= 1 \
        \ Other values will generated exceptions
      operationId: getOrderById
      produces:
        - application/json
      parameters:
        - name: person_id
          in: path
          description: ID of the person to retrieve
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/Person'
        400:
          description: Invalid ID supplied
        404:
          description: person not found

definitions:
  Person:
    type: object
    required:
      - id
      - first_name
      - last_name
      - company_name
    properties:
      id:
        type: integer
        format: int64
        example: 1
      first_name:
        type: string
        example: Frank
      last_name:
        type: string
        example: Shader
      company_name:
        type: string
        example: Hampton, Hampton and McQuill
      manufacturer:
        $ref: '#/definitions/Person'
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /pascalito007/persons/1.0.0
schemes:
  - https
